STRIPE_SECRET_KEY = ENV["STRIPE_SECRET_KEY"]
STRIPE_PRICE_ID = ENV["STRIPE_PRICE_ID"]
STRIPE_WEBHOOK_SECRET = ENV["STRIPE_WEBHOOK_SECRET"]

if STRIPE_SECRET_KEY.present?
  require "stripe"
  Stripe.api_key = STRIPE_SECRET_KEY
end
